### PR TITLE
Tlddoc 

### PR DESCRIPTION
**Pull request by NKjoep**
Added the maven plugin for generating the tag library documentation ( mvn taglib:taglibdoc )

### CODE REVIEW

**Comment by trumbitta** [comment]
Hey @NKjoep! Nice and useful addition!

Have you checked if the generated docs go into the `-javadoc` jar at package / install time?
If not, can you configure it to do so?

Also, how about using `${project.build.directory}` instead of `target`?
I think there are a bunch of hardcoded `target` occurences spreaded in our files, but I'd like to get rid of them over time.

**Comment by trumbitta** [comment]
Last minute follow-up: also found (http://maven.apache.org/plugins/maven-site-plugin/site-mojo.html) this promising property: `${project.reporting.outputDirectory}`
Could you check if it resolves to `target/site` ?

**Comment by NKjoep** [comment]
I checked and it's confirmed that ${project.reporting.outputDirectory}  points to <code>target/site</code>, so in the taglibdoc plugin it's better use:

``` xml
<tldDocDir>${project.reporting.outputDirectory}/tlddocs</tldDocDir>
```

However the generated docs won't be included in the javadoc package. I think we have to configure something in the pom.xml.

**Comment by trumbitta** [comment]
Mmm sounds promising...

Will take a look asap :)

**Comment by trumbitta** [comment]
Hey, I checked your pull-request and everything looks just fine!
A very useful addition, indeed!

BTW, I'd like to merge this only after closing #12 for being more sure that everything goes in place smoothly.

**Comment by NKjoep** [comment]
see b6c61c6c14c68b1ed7b2aa4c25f0fa7d52291761

**Pull request closed without merging**
